### PR TITLE
Fixing the build issue.

### PR DESCRIPTION
**Pull request by georgethomas111**

### CODE REVIEW

**Comment by georgethomas111** [comment]
@johnhof Hey there was a small bug. Could you merge as I do not have access.

**Comment by johnhof** [comment]
@georgethomas111 you went tabs to spaces here. can you fix those?

**Comment by georgethomas111** [comment]
Actually It was `gofmt` running automatically which did it.  @johnhof  Corrected.

**Comment by johnhof** [comment]
thanks!

**Pull request merged**
